<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>BLOG | Authentification</title>
        <link href="https://fonts.googleapis.com/css?family=Baloo+2&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="./css/style.css">
        <link rel="stylesheet" href="./css/menu.css">
	</head>
	<body>
        <div class="wrap">
            <div class="menu-wrap">
                <?php include('./php-include/nav.phtml'); ?>
                <header class="showcase">
                    <div class="container showcase-inner">
                        <h1>Connexion</h1>
                        <form action="index.php" method="post" class="formLogin">
                            <div>
                                <input type="text" name="pseudo" placeholder="Adresse mail" class="form-control"/>
                            </div>
                            <div>
                                <input type="password" name="password" placeholder="Mot de passe" class="form-control"/>
                            </div>
                            <button type="submit" class="btn">Se connecter</button>
                            <p>Vous n'avez pas de compte ?</p>
                            <div> 
                                <a href="../sign-up.php">Créer un compte</a>
                            </div>
                            
                        </form>
                        <?php if(isset($erreur)): ?><p class="erreur"><?= $erreur ?></p><?php endif?>
                    </div>
                </header>
            </div>
        </div>
	</body>
</html>